on: [push]

name: build

jobs:
  build:
    name: Build docker image 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: philips-software/docker-ci-scripts@REPO-tag
      with:
        dockerfile: 1
        image-name: test
        tags: 'latest 1 1.2 1.2.1'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: jeroenknoops
