on: [push]

name: build

jobs:
  build:
    name: Build docker image 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build Docker Image
    - uses: github.com/jeroenknoops/docker-ci-scripts@4f73d560ba065c110914500f47b6cff94e5a21aa
      with:
        dockerfile: 1
        tags: 'test test:1 test:1.2 test:1.2.1'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}

